### ISSUE TITLE
Implement Github Actions for Desktop Repository

### ISSUE THREAD

**Issue by JSmith2023** [EECE3093C/under-the-c-desktop#18]

**Comment by natruffles** [comment]
@JSmith2023 we do not need to implement a PlatformIO IDE run command as a GitHub Action in this repository. Only the controller repository is using PlatformIO IDE to push code to our microcontroller.
On this repository, I would prefer if we instead built and ran the project using CMake as a GitHub action, or ran a linter of some sort. Linked [here](https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/) is a tutorial for building a C++ project using CMake in a GitHub Action.

**Comment by JSmith2023** [comment]
Deleted platformIO action, was created on this repository by mistake.
