### ISSUE TITLE
Create gitignore for desktop

### ISSUE THREAD

**Issue by ZachUCLamparyk** [EECE3093C/under-the-c-desktop#19]
Ignore ".vscode". Done after CMAKE file as desktop project only compiles with change made in .vscode

**Comment by natruffles** [comment]
Hi Zach,
The professor showed us [this website](https://www.toptal.com/developers/gitignore) in class that we can use to generate good .gitignore files based on the IDE, OS, and languages that we are using.
I would recommend using prompts like "VisualStudioCode", "CMake", "C++", and any others you can think of.
