### ISSUE TITLE
Update README with updated domain model and software/hardware architecture

### ISSUE THREAD

**Issue by natruffles** [EECE3093C/under-the-c-desktop#33]
This will be done near the end of the iteration once we have fully fleshed out what libraries we will be using for unit testing, etc.

**Comment by marti6j8** [comment]
These are the commands we need to run in the terminal everytime a change is made in the code in order to rebuild the executable:
```
cd build
cmake ..
make all
./src/Weatherlite_run
./tst/Weatherlite_tst
```
