### ISSUE TITLE
Add Doctest C++ unit testing framework to repo

### ISSUE THREAD

**Issue by natruffles** [EECE3093C/under-the-c-desktop#35]
This issue should be resolved simply by adding the "doctest.h" header file to our repo.

The tutorial for download/use of this unit testing framework can be found [here](https://github.com/doctest/doctest/blob/master/doc/markdown/tutorial.md).

**Comment by natruffles** [comment]
Hi Zach,
I heard that you were having trouble getting the doctest library to compile using CMake. I would recommend reading through [this markdown file](https://github.com/doctest/doctest/blob/master/doc/markdown/build-systems.md). If you already have the doctest library downloaded to your repo, you can follow the steps near the top of the document. If you don't have the doctest library downloaded to your repo, you can still use CMake to download the library from the internet and compile every time. Up to you what you want to purse. Let me know if you have any questions.

**Comment by JSmith2023** [comment]
We decided that the doctest testing suite was ill-suited for the job, and have replaced with the gtest suite.

**Comment by ZachUCLamparyk** [comment]
I second Josh's statement.
