### ISSUE TITLE
Connect OpenWeatherAPI to C++ command line application

### ISSUE THREAD

**Issue by natruffles** [EECE3093C/under-the-c-desktop#7]
The tutorial should cover how it works and how to use it on base C++ (desktop).

**Comment by natruffles** [comment]
I think I removed this from the project by mistake, we should still have an issue to connect the OpenWeatherAPI to our desktop application. No need to create a tutorial for use, just implement the functionality (with proper documentation ofc).

**Comment by marti6j8** [comment]
https://github.com/jpbarrette/curlpp/releases/tag/v0.8.1
Here is the link to download curlpp, we should be able to use this to make http requests

**Comment by marti6j8** [comment]
https://github.com/jpbarrette/curlpp/blob/master/doc/guide.pdf
Here is the guide for the library, it should detail the commands we need to use and how to implement the library

**Comment by natruffles** [comment]
Hi Jason, thanks for stepping up on this!
I didn't realize that we weren't able to use the curl library directly as it was designed for a command line interface!
You could pick between [libcurl](https://curl.se/libcurl/) or the library that you mentioned above, and I think that the library above that you're using is better because it's even more suited for guys like us who are less experienced with this kind of programming.

**Comment by natruffles** [comment]
This issue should be completed after #22, but before #23.

**Comment by marti6j8** [comment]
@ZachUCLamparyk Are you free to help me configure the CMake file for the library today around 1:30?

**Comment by ZachUCLamparyk** [comment]
@marti6j8 Sorry, I'll be working with Josh until 5:30pm. Want to work on it tomorrow at 1:30? We can do sooner or later if need be, just throwing out a time.
